
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: 123shopper
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432" 
    ports:
      - "5432:5432"
  
  app:
    build: .
    depends_on:
      - db
    
    ports:
      - "3000:3000"
    restart: always

volumes: 
  db: